[project]
name = "python-rec-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.4",
    "yfinance>=0.2.50",
]

[dependency-groups]
dev = [
    "ruff>=0.8.2",
]
